import type { Signalement, Category, DashboardStats, StatusHistory } from "@signalicity/shared";

export const MOCK_CATEGORIES: Category[] = [
  { id: "c1", name: "Voirie", slug: "voirie", icon: "road", color: "#6366F1", service_id: "s1" },
  { id: "c2", name: "Proprete", slug: "proprete", icon: "trash", color: "#F59E0B", service_id: "s2" },
  { id: "c3", name: "Eclairage", slug: "eclairage", icon: "lightbulb", color: "#FBBF24", service_id: "s3" },
  { id: "c4", name: "Espaces verts", slug: "espaces-verts", icon: "tree", color: "#10B981", service_id: "s4" },
  { id: "c5", name: "Mobilier urbain", slug: "mobilier-urbain", icon: "bench", color: "#8B5CF6", service_id: "s5" },
  { id: "c6", name: "Stationnement", slug: "stationnement", icon: "car", color: "#EF4444", service_id: "s1" },
  { id: "c7", name: "Nuisances", slug: "nuisances", icon: "volume-x", color: "#EC4899", service_id: "s5" },
  { id: "c8", name: "Autre", slug: "autre", icon: "help-circle", color: "#6B7280", service_id: "s5" },
];

export const MOCK_SIGNALEMENTS: Signalement[] = [
  {
    id: "sig-001",
    created_at: "2026-05-20T08:00:00.000Z",
    updated_at: "2026-05-20T08:00:00.000Z",
    user_id: null,
    guest_email: "jean.dupont@email.fr",
    category_id: "c1",
    title: "Nid de poule rue de Paris",
    description: "Important nid de poule sur la chaussee, dangereux pour les velos.",
    ai_description: "Degradation de chaussee : nid de poule de taille moyenne sur voie principale.",
    photo_url: "https://placehold.co/800x600/6366F1/white?text=Voirie",
    photo_after_url: null,
    latitude: 48.879,
    longitude: 2.1345,
    address: "15 Rue de Paris, 78290 Croissy-sur-Seine",
    status: "received",
    severity: "high",
    assigned_service_id: "s1",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: null,
    resolved_at: null,
  },
  {
    id: "sig-002",
    created_at: "2026-05-19T10:00:00.000Z",
    updated_at: "2026-05-19T14:00:00.000Z",
    user_id: null,
    guest_email: "marie.martin@email.fr",
    category_id: "c2",
    title: "Poubelle renversee avenue de Verdun",
    description: "Poubelle de tri renversee, dechets au sol.",
    ai_description: "Container de tri selectif renverse. Dechets disperses sur le trottoir.",
    photo_url: "https://placehold.co/800x600/F59E0B/white?text=Proprete",
    photo_after_url: null,
    latitude: 48.8775,
    longitude: 2.138,
    address: "8 Avenue de Verdun, 78290 Croissy-sur-Seine",
    status: "in_progress",
    severity: "medium",
    assigned_service_id: "s2",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: "Equipe de nettoyage prevenue",
    resolved_at: null,
  },
  {
    id: "sig-003",
    created_at: "2026-05-15T09:00:00.000Z",
    updated_at: "2026-05-17T11:00:00.000Z",
    user_id: null,
    guest_email: "pierre.durand@email.fr",
    category_id: "c3",
    title: "Lampadaire en panne",
    description: "Lampadaire eteint depuis plusieurs jours, zone sombre le soir.",
    ai_description: "Eclairage public defaillant : lampadaire hors service.",
    photo_url: "https://placehold.co/800x600/FBBF24/white?text=Eclairage",
    photo_after_url: "https://placehold.co/800x600/10B981/white?text=Repare",
    latitude: 48.88,
    longitude: 2.136,
    address: "22 Rue Jean Jaures, 78290 Croissy-sur-Seine",
    status: "resolved",
    severity: "medium",
    assigned_service_id: "s3",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: "Ampoule remplacee le 15/05",
    resolved_at: "2026-05-17T11:00:00.000Z",
  },
  {
    id: "sig-004",
    created_at: "2026-05-20T07:00:00.000Z",
    updated_at: "2026-05-20T07:00:00.000Z",
    user_id: null,
    guest_email: "sophie.leroy@email.fr",
    category_id: "c4",
    title: "Branche cassee parc Chanorier",
    description: "Grosse branche cassee bloquant partiellement le chemin.",
    ai_description: "Branche d'arbre tombee sur sentier pieton dans espace vert public.",
    photo_url: "https://placehold.co/800x600/10B981/white?text=Espaces+Verts",
    photo_after_url: null,
    latitude: 48.8788,
    longitude: 2.132,
    address: "Parc Chanorier, 78290 Croissy-sur-Seine",
    status: "received",
    severity: "high",
    assigned_service_id: "s4",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: null,
    resolved_at: null,
  },
  {
    id: "sig-005",
    created_at: "2026-05-18T10:00:00.000Z",
    updated_at: "2026-05-19T10:00:00.000Z",
    user_id: null,
    guest_email: "lucas.moreau@email.fr",
    category_id: "c5",
    title: "Banc casse place de la Mairie",
    description: "Assise du banc brisee, risque de blessure.",
    ai_description: "Mobilier urbain endommage : banc public avec assise fracturee.",
    photo_url: "https://placehold.co/800x600/8B5CF6/white?text=Mobilier",
    photo_after_url: null,
    latitude: 48.8783,
    longitude: 2.1372,
    address: "Place de la Mairie, 78290 Croissy-sur-Seine",
    status: "in_progress",
    severity: "low",
    assigned_service_id: "s5",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: "Commande de piece en cours",
    resolved_at: null,
  },
  {
    id: "sig-006",
    created_at: "2026-05-20T09:30:00.000Z",
    updated_at: "2026-05-20T09:30:00.000Z",
    user_id: null,
    guest_email: "emma.petit@email.fr",
    category_id: "c6",
    title: "Stationnement genant rue du Bac",
    description: "Vehicule stationne sur le trottoir, passage impossible pour les poussettes.",
    ai_description: "Stationnement irregulier bloquant la circulation pietonne.",
    photo_url: "https://placehold.co/800x600/EF4444/white?text=Stationnement",
    photo_after_url: null,
    latitude: 48.877,
    longitude: 2.14,
    address: "5 Rue du Bac, 78290 Croissy-sur-Seine",
    status: "received",
    severity: "medium",
    assigned_service_id: "s1",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: null,
    resolved_at: null,
  },
  {
    id: "sig-007",
    created_at: "2026-05-13T08:00:00.000Z",
    updated_at: "2026-05-15T09:00:00.000Z",
    user_id: null,
    guest_email: "thomas.garcia@email.fr",
    category_id: "c7",
    title: "Nuisances sonores chantier",
    description: "Travaux de chantier tres tot le matin avant 7h.",
    ai_description: "Nuisances sonores : activite de chantier en dehors des horaires autorises.",
    photo_url: "https://placehold.co/800x600/EC4899/white?text=Nuisances",
    photo_after_url: null,
    latitude: 48.876,
    longitude: 2.135,
    address: "12 Rue des Gabillons, 78290 Croissy-sur-Seine",
    status: "resolved",
    severity: "low",
    assigned_service_id: "s5",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: "Rappel fait a l'entreprise de BTP",
    resolved_at: "2026-05-15T09:00:00.000Z",
  },
  {
    id: "sig-008",
    created_at: "2026-05-17T11:00:00.000Z",
    updated_at: "2026-05-18T10:00:00.000Z",
    user_id: null,
    guest_email: "julie.bernard@email.fr",
    category_id: "c1",
    title: "Trottoir degrade rue de Seine",
    description: "Dalles soulevees par les racines, risque de chute.",
    ai_description: "Degradation du trottoir par soulevement de dalles.",
    photo_url: "https://placehold.co/800x600/6366F1/white?text=Voirie+2",
    photo_after_url: null,
    latitude: 48.8795,
    longitude: 2.139,
    address: "30 Rue de Seine, 78290 Croissy-sur-Seine",
    status: "in_progress",
    severity: "high",
    assigned_service_id: "s1",
    assigned_agent_id: null,
    duplicate_of: null,
    internal_notes: "Intervention planifiee semaine prochaine",
    resolved_at: null,
  },
];

export const MOCK_STATS: DashboardStats = {
  total_signalements: 47,
  resolved_count: 18,
  in_progress_count: 14,
  received_count: 15,
  avg_resolution_hours: 52,
  resolution_rate: 38.3,
};

export const MOCK_STATUS_HISTORY: StatusHistory[] = [
  { id: "h1", signalement_id: "sig-001", old_status: null, new_status: "received", changed_by: "system", note: "Signalement recu", created_at: "2026-05-20T08:00:00.000Z" },
  { id: "h2", signalement_id: "sig-002", old_status: null, new_status: "received", changed_by: "system", note: "Signalement recu", created_at: "2026-05-19T10:00:00.000Z" },
  { id: "h3", signalement_id: "sig-002", old_status: "received", new_status: "in_progress", changed_by: "agent", note: "Pris en charge", created_at: "2026-05-19T14:00:00.000Z" },
  { id: "h4", signalement_id: "sig-003", old_status: null, new_status: "received", changed_by: "system", note: "Signalement recu", created_at: "2026-05-15T09:00:00.000Z" },
  { id: "h5", signalement_id: "sig-003", old_status: "received", new_status: "in_progress", changed_by: "agent", note: "Intervention planifiee", created_at: "2026-05-16T10:00:00.000Z" },
  { id: "h6", signalement_id: "sig-003", old_status: "in_progress", new_status: "resolved", changed_by: "agent", note: "Ampoule remplacee", created_at: "2026-05-17T11:00:00.000Z" },
];

export function getCategoryById(id: string): Category | undefined {
  return MOCK_CATEGORIES.find((c) => c.id === id);
}

export const MOCK_CHART_DATA = [
  { date: "Lun", received: 4, resolved: 2 },
  { date: "Mar", received: 6, resolved: 3 },
  { date: "Mer", received: 3, resolved: 5 },
  { date: "Jeu", received: 7, resolved: 4 },
  { date: "Ven", received: 5, resolved: 6 },
  { date: "Sam", received: 2, resolved: 1 },
  { date: "Dim", received: 1, resolved: 2 },
];
